package tempconvertGUI;

/**
 *
 * @author Matthew
 */
import java.text.*;
import javax.swing.*;
import tempconvert.*;

public class TempConvertMainGUI extends javax.swing.JFrame {

    private final String ERROR_MSG = "Please Enter a number value";
    private final String FARH_MSG = "Temp in Farh ";
    private final String CEL_MSG = "Temp in Celcius ";

    private final NumberFormat nf = new DecimalFormat("0.##");

    private TempCalc tempConverts;

    /**
     * Creates new form NewJFrame
     */
    public TempConvertMainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTempPrompt = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        cmbBoxTempSwitch = new javax.swing.JComboBox();
        btnConvert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblTempPrompt.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTempPrompt.setText("Enter Temp");

        cmbBoxTempSwitch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "F to C", "C to F"}));

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTempPrompt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTemp)
                    .addComponent(cmbBoxTempSwitch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConvert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTempPrompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBoxTempSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConvert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        try {
            if (cmbBoxTempSwitch.getSelectedItem() == "F to C") {
                tempConverts = new FarhToCelStrategy();
                double calcTemp = tempConverts.convertTemp(Double.parseDouble(txtTemp.getText()));
                JOptionPane.showMessageDialog(btnConvert, CEL_MSG + nf.format(calcTemp));
            } else if (cmbBoxTempSwitch.getSelectedItem() == "C to F") {
                tempConverts = new CelToFarhStrategy();
                double calcTemp = tempConverts.convertTemp(Double.parseDouble(txtTemp.getText()));
                JOptionPane.showMessageDialog(btnConvert, FARH_MSG + nf.format(calcTemp));
            }
        } catch (NullPointerException | NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, ERROR_MSG);
        }
    }//GEN-LAST:event_btnConvertActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvert;
    private javax.swing.JComboBox cmbBoxTempSwitch;
    private javax.swing.JLabel lblTempPrompt;
    private javax.swing.JTextField txtTemp;
    // End of variables declaration//GEN-END:variables
}
